// SPDX-License-Identifier: MIT OR Apache-2.0
//
// Tiny end-to-end demo. Run from the repo root with:
//
//     cargo build --manifest-path fulgur-native/Cargo.toml
//     dotnet run --project examples/HelloFulgur -p:HostArchitecture=x64
//
// Produces `hello.pdf` next to the binary.

using System;
using FulgurNET;

var html = """
    <html>
      <head>
        <style>
          body { font-family: sans-serif; margin: 2cm; }
          h1 { color: #2b5cb8; }
        </style>
      </head>
      <body>
        <h1>Hello from FulgurNET!</h1>
        <p>This PDF was generated by the fulgur Rust engine, called
           through a zero-copy FFI shim built with csbindgen.</p>
      </body>
    </html>
    """;

var bytes = FulgurPdf.FromHtml(html);
var outPath = System.IO.Path.Combine(AppContext.BaseDirectory, "hello.pdf");
System.IO.File.WriteAllBytes(outPath, bytes);

Console.WriteLine($"Wrote {bytes.Length} bytes to {outPath}");
Console.WriteLine($"Native engine version: {FulgurPdf.NativeVersion}");
