// SPDX-License-Identifier: MIT OR Apache-2.0
//
// FFI-safe byte buffer declaration. The Rust side (`fulgur-native/src/buffer.rs`)
// owns the heap allocation and the matching `fulgur_free_buffer` release
// call. The C# side treats the struct as an opaque borrow that must be
// consumed before `free` is called.
//
// This file is NOT auto-generated by csbindgen — the generator emits
// `byte*` for opaque pointers, but for our `ByteBuffer` case the layout
// is fully known and we want the struct to be materializable (so the
// C# `Span<byte>` helper can read `ptr` / `length` directly). We declare
// it once, by hand, in `LayoutKind.Sequential` matching the Rust
// `#[repr(C)]` layout. csbindgen recognizes the type by its fields and
// uses the same shape in the generated `NativeMethods.g.cs` — so
// `ByteBuffer fulgur_render_html(...)` returns OUR struct, not a
// duplicate.

using System.Runtime.InteropServices;

namespace FulgurNET;

/// <summary>
/// Opaque FFI handle for an owned byte buffer allocated on the Rust side.
/// Field order MUST match `ByteBuffer` in <c>fulgur-native/src/buffer.rs</c>:
///   ptr: *mut u8, length: i32, capacity: i32
/// </summary>
[StructLayout(LayoutKind.Sequential)]
public unsafe partial struct ByteBuffer
{
    /// <summary>Heap pointer owned by the Rust allocator. Do not free from C#.</summary>
    public byte* ptr;

    /// <summary>Number of valid bytes at <see cref="ptr"/>.</summary>
    public int length;

    /// <summary>Underlying allocation size in bytes (used by the Rust destructor).</summary>
    public int capacity;
}
