// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace FulgurNET
{
    public static unsafe partial class NativeMethods
    {
        const string __DllName = "fulgur_native";





        /// <summary>
        ///  Convert an HTML string to PDF bytes using default settings.
        ///
        ///  Input is a UTF-8 byte slice (`html_ptr` / `html_len`). Returned
        ///  `ByteBuffer` ownership transfers to the caller; it must be released
        ///  with `fulgur_free_buffer`.
        ///
        ///  Returns a buffer with `length == 0` on any failure — see module docs.
        ///  (`ptr` is not guaranteed to be null on the failure path; the C#
        ///  wrapper checks `length` only.)
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fulgur_render_html", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern ByteBuffer fulgur_render_html(byte* html_ptr, int html_len);

        /// <summary>
        ///  Release a `ByteBuffer` previously returned by any `fulgur_render_*`
        ///  function. After this call, the buffer's `ptr` MUST NOT be used.
        ///
        ///  Calling `free_buffer` on a zero-length / null buffer is a no-op.
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fulgur_free_buffer", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern void fulgur_free_buffer(ByteBuffer buffer);

        /// <summary>
        ///  Return the version of the bundled fulgur engine, as a NUL-terminated
        ///  UTF-8 C string. The returned pointer is to a process-lifetime static
        ///  — the caller MUST NOT free it.
        ///
        ///  This is mostly useful for diagnostics and NuGet smoke tests, but we
        ///  expose it from day one because the .NET package version needs to
        ///  match (and we can't read Cargo.toml at runtime from C#).
        /// </summary>
        [DllImport(__DllName, EntryPoint = "fulgur_version", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern byte* fulgur_version();


    }



}
